package com.bugplatform.core;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import java.util.UUID;

@Entity
public class BugReport {
    
    @Id
    private String id;
    private String title;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String severity;
    private String status;
    
    @Column(columnDefinition = "TEXT")
    private String originalCode;
    
    @Column(columnDefinition = "TEXT")
    private String patchedCode;
    
    @Column(columnDefinition = "TEXT")
    private String unitTestCode; // Automated unit test generated by AI
    private String githubPrLink;
    private int complexityScore;
    private String maintainability;
    private int tokensUsed;

    private String aiConfidence;
    
    @Column(columnDefinition = "TEXT")
    private String aiExplanation;
    
    private String duplicateOf;
    
    @Column(columnDefinition = "TEXT")
    private String evolutionTimeline;

    private String technicalDomain;
    private String secondaryDomain;
    private String componentName;
    private String domainConfidence;
    @Column(columnDefinition = "TEXT")
    private String domainReasoning;

    private String priority;
    private String bugType;
    private String createdAt;
    private String resolvedAt;
    private String fileLocation;
    private String moduleName;

    private String lineNumber;
    private String functionName;
    private String rootCause;
    private String trackingStatus;

    // --- New Project Ecosystem fields ---
    private String projectLanguages;
    private String projectFrontendStack;
    private String projectBackendStack;
    private String projectAlgorithms;

    public BugReport() {}

    public BugReport(String title, String description, String severity) {
        this.id = UUID.randomUUID().toString();
        this.title = title;
        this.description = description;
        this.severity = severity;
        this.status = "OPEN";
        this.originalCode = "public void process(String input) {\n    if(input != null) {\n        for(char c : input.toCharArray()) {\n            if(c == 'X') { processX(); }\n        }\n    }\n}";
        this.patchedCode = "public void process(String input) {\n    if (input == null) return;\n    input.chars().filter(c -> c == 'X').forEach(c -> processX());\n}";
        this.unitTestCode = "@Test\npublic void testProcessSafety() {\n    assertDoesNotThrow(() -> service.process(null));\n    assertDoesNotThrow(() -> service.process(\"X-TEST\"));\n}";
        this.githubPrLink = "Pending AI Auto-Fix";
        this.complexityScore = 6;
        this.maintainability = "Moderate (Optimized by AI)";
        this.tokensUsed = 1420;

        // Analytics dynamic generation (Domain properties will be populated by OpenAIService)
        
        String[] priorities = {"P0", "P1", "P2", "P3"};
        this.priority = priorities[(int)(Math.random() * priorities.length)];
        
        String[] types = {"Logic", "UI", "Security", "Performance", "Data"};
        this.bugType = types[(int)(Math.random() * types.length)];
        
        this.createdAt = java.time.LocalDateTime.now().minusDays((int)(Math.random() * 10)).toString();
        // If bug is created as OPEN, resolvedAt is null initially. We mock it for some cases if needed, but constructor makes it OPEN.
        this.resolvedAt = null; 
        
        this.fileLocation = "src/main/java/com/bugplatform/core/Unknown.java";
        this.moduleName = "Core Engine";
        
        this.lineNumber = "42";
        this.functionName = "processRequest()";
        this.rootCause = "Unchecked NullLiteral";
        this.trackingStatus = "Fix Applied"; // mock status
    }

    // --- Getters & Setters ---
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public String getOriginalCode() { return originalCode; }
    public void setOriginalCode(String originalCode) { this.originalCode = originalCode; }
    public String getPatchedCode() { return patchedCode; }
    public void setPatchedCode(String patchedCode) { this.patchedCode = patchedCode; }
    public String getUnitTestCode() { return unitTestCode; }
    public void setUnitTestCode(String unitTestCode) { this.unitTestCode = unitTestCode; }
    public String getGithubPrLink() { return githubPrLink; }
    public void setGithubPrLink(String githubPrLink) { this.githubPrLink = githubPrLink; }
    public int getComplexityScore() { return complexityScore; }
    public void setComplexityScore(int complexityScore) { this.complexityScore = complexityScore; }
    public String getMaintainability() { return maintainability; }
    public void setMaintainability(String maintainability) { this.maintainability = maintainability; }
    public int getTokensUsed() { return tokensUsed; }
    public void setTokensUsed(int tokensUsed) { this.tokensUsed = tokensUsed; }
    
    public String getAiConfidence() { return aiConfidence; }
    public void setAiConfidence(String aiConfidence) { this.aiConfidence = aiConfidence; }
    
    public String getAiExplanation() { return aiExplanation; }
    public void setAiExplanation(String aiExplanation) { this.aiExplanation = aiExplanation; }
    
    public String getDuplicateOf() { return duplicateOf; }
    public void setDuplicateOf(String duplicateOf) { this.duplicateOf = duplicateOf; }
    
    public String getEvolutionTimeline() { return evolutionTimeline; }
    public void setEvolutionTimeline(String evolutionTimeline) { this.evolutionTimeline = evolutionTimeline; }
    
    public String getTechnicalDomain() { return technicalDomain; }
    public void setTechnicalDomain(String technicalDomain) { this.technicalDomain = technicalDomain; }
    
    public String getSecondaryDomain() { return secondaryDomain; }
    public void setSecondaryDomain(String secondaryDomain) { this.secondaryDomain = secondaryDomain; }
    
    public String getComponentName() { return componentName; }
    public void setComponentName(String componentName) { this.componentName = componentName; }
    
    public String getDomainConfidence() { return domainConfidence; }
    public void setDomainConfidence(String domainConfidence) { this.domainConfidence = domainConfidence; }
    
    public String getDomainReasoning() { return domainReasoning; }
    public void setDomainReasoning(String domainReasoning) { this.domainReasoning = domainReasoning; }
    
    public String getPriority() { return priority; }
    public void setPriority(String priority) { this.priority = priority; }
    
    public String getBugType() { return bugType; }
    public void setBugType(String bugType) { this.bugType = bugType; }
    
    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }
    
    public String getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(String resolvedAt) { this.resolvedAt = resolvedAt; }
    
    public String getFileLocation() { return fileLocation; }
    public void setFileLocation(String fileLocation) { this.fileLocation = fileLocation; }
    
    public String getModuleName() { return moduleName; }
    public void setModuleName(String moduleName) { this.moduleName = moduleName; }

    public String getLineNumber() { return lineNumber; }
    public void setLineNumber(String lineNumber) { this.lineNumber = lineNumber; }

    public String getFunctionName() { return functionName; }
    public void setFunctionName(String functionName) { this.functionName = functionName; }

    public String getRootCause() { return rootCause; }
    public void setRootCause(String rootCause) { this.rootCause = rootCause; }

    public String getTrackingStatus() { return trackingStatus; }
    public void setTrackingStatus(String trackingStatus) { this.trackingStatus = trackingStatus; }

    public String getProjectLanguages() { return projectLanguages; }
    public void setProjectLanguages(String projectLanguages) { this.projectLanguages = projectLanguages; }
    public String getProjectFrontendStack() { return projectFrontendStack; }
    public void setProjectFrontendStack(String projectFrontendStack) { this.projectFrontendStack = projectFrontendStack; }
    public String getProjectBackendStack() { return projectBackendStack; }
    public void setProjectBackendStack(String projectBackendStack) { this.projectBackendStack = projectBackendStack; }
    public String getProjectAlgorithms() { return projectAlgorithms; }
    public void setProjectAlgorithms(String projectAlgorithms) { this.projectAlgorithms = projectAlgorithms; }
}