package com.bugplatform.core;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import java.util.UUID;

@Entity
public class BugReport {
    
    @Id
    private String id;
    private String title;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String severity;
    private String status;
    
    @Column(columnDefinition = "TEXT")
    private String originalCode;
    
    @Column(columnDefinition = "TEXT")
    private String patchedCode;
    
    @Column(columnDefinition = "TEXT")
    private String unitTestCode; // Automated unit test generated by AI
    private String githubPrLink;
    private int complexityScore;
    private String maintainability;
    private int tokensUsed;

    private String aiConfidence;
    
    @Column(columnDefinition = "TEXT")
    private String aiExplanation;
    
    private String duplicateOf;
    
    @Column(columnDefinition = "TEXT")
    private String evolutionTimeline;

    public BugReport() {}

    public BugReport(String title, String description, String severity) {
        this.id = UUID.randomUUID().toString();
        this.title = title;
        this.description = description;
        this.severity = severity;
        this.status = "OPEN";
        this.originalCode = "public void process(String input) {\n    if(input != null) {\n        for(char c : input.toCharArray()) {\n            if(c == 'X') { processX(); }\n        }\n    }\n}";
        this.patchedCode = "public void process(String input) {\n    if (input == null) return;\n    input.chars().filter(c -> c == 'X').forEach(c -> processX());\n}";
        this.unitTestCode = "@Test\npublic void testProcessSafety() {\n    assertDoesNotThrow(() -> service.process(null));\n    assertDoesNotThrow(() -> service.process(\"X-TEST\"));\n}";
        this.githubPrLink = "Pending AI Auto-Fix";
        this.complexityScore = 6;
        this.maintainability = "Moderate (Optimized by AI)";
        this.tokensUsed = 1420;
    }

    // --- Getters & Setters ---
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public String getOriginalCode() { return originalCode; }
    public void setOriginalCode(String originalCode) { this.originalCode = originalCode; }
    public String getPatchedCode() { return patchedCode; }
    public void setPatchedCode(String patchedCode) { this.patchedCode = patchedCode; }
    public String getUnitTestCode() { return unitTestCode; }
    public void setUnitTestCode(String unitTestCode) { this.unitTestCode = unitTestCode; }
    public String getGithubPrLink() { return githubPrLink; }
    public void setGithubPrLink(String githubPrLink) { this.githubPrLink = githubPrLink; }
    public int getComplexityScore() { return complexityScore; }
    public void setComplexityScore(int complexityScore) { this.complexityScore = complexityScore; }
    public String getMaintainability() { return maintainability; }
    public void setMaintainability(String maintainability) { this.maintainability = maintainability; }
    public int getTokensUsed() { return tokensUsed; }
    public void setTokensUsed(int tokensUsed) { this.tokensUsed = tokensUsed; }
    
    public String getAiConfidence() { return aiConfidence; }
    public void setAiConfidence(String aiConfidence) { this.aiConfidence = aiConfidence; }
    
    public String getAiExplanation() { return aiExplanation; }
    public void setAiExplanation(String aiExplanation) { this.aiExplanation = aiExplanation; }
    
    public String getDuplicateOf() { return duplicateOf; }
    public void setDuplicateOf(String duplicateOf) { this.duplicateOf = duplicateOf; }
    
    public String getEvolutionTimeline() { return evolutionTimeline; }
    public void setEvolutionTimeline(String evolutionTimeline) { this.evolutionTimeline = evolutionTimeline; }
}